# Generated by Django 2.2 on 2019-08-01 05:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicle', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factura_number', models.CharField(max_length=12)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('end_hour', models.TimeField()),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_hour', models.TimeField()),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vehicle.Vehicle')),
            ],
        ),
    ]
